title: Pangenome Bio Hacking 2025 Workshop
description: Pangenome Bio Hacking 2025 Workshop
baseurl: /
url: https://algolab.github.io/pgbh2025

permalink: pretty
# theme: jekyll-nagymaros
remote_theme: piazzai/jekyll-nagymaros@v3.3.1

home: /
copyright: Place Holder
indexing: true

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

sass:
  sourcemap: never
